services:
  - type: web
    name: system-data-school
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: OWNER_USERNAME
        sync: false
      - key: OWNER_PASSWORD
        sync: false
      - key: SUPABASE_BUCKET
        value: school-files
      - key: rnd_3HOwiW0ptRZrHES4CvtYfijqLb8F
        sync: false
    headers:
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
